name: Test

on: push

jobs:
    ubuntu:
     runs-on: ubuntu-latest
     steps:
     - run: date
    windows:
     runs-on: windows-latest
     steps:
     - run: date
    macos:
     runs-on: macos-latst
     steps:
     - run: date
